"use client";
import { FC } from 'react';
import Head from 'next/head';
import Main from '@/Components/Main';

const Home: FC = () => {
    return (
        <>
            <Head>
                <title>TODO App Next.JS 13</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Main />
            </main>
        </>
    )
};

export default Home;